import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "../../componentes/authContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Turn on the beck",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider> 
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
